var metadata = [{
    "id": "EPI_1",
    "tab": "epiTabs",
    "name": "Deaths last 7 days",
    "unit": "per 100k",
    "source": "World Health Organization",
    "source_file": "epi",
    "risk_dir": "asc",
    "risk_1": "1",
    "risk_2": "25",
    "risk_3": "50",
    "risk_4": "75",
    "risk_level": "4",
    "value": "106",
    "count": "193",
    "total": "20507",
    "mean": "106",
    "stddev": "184",
    "max": "935",
    "min": "0",
    "metric": "epi_cases_last_7_days_100k"
  },
  {
    "id": "EPI_2",
    "tab": "epiTabs",
    "name": "Cases last 7 days",
    "unit": "per 100k",
    "source": "World Health Organization",
    "source_file": "epi",
    "risk_dir": "asc",
    "risk_1": "10",
    "risk_2": "50",
    "risk_3": "100",
    "risk_4": "150",
    "risk_level": "4",
    "value": "247",
    "count": "193",
    "total": "47707",
    "mean": "247",
    "stddev": "914",
    "max": "8227",
    "min": "0",
    "metric": "epi_deaths_last_7_days"
  },
  {
    "id": "Vx_1",
    "tab": "vxTabs",
    "name": "Vaccinated  +1  dose",
    "unit": "%",
    "source": "World Health Organization",
    "source_file": "ivb",
    "risk_dir": "desc",
    "risk_2": "60",
    "risk_3": "40",
    "risk_4": "20",
    "risk_5": "10",
    "risk_level": "2",
    "value": "42",
    "count": "190",
    "total": "8141",
    "mean": "42",
    "stddev": "27",
    "max": "120",
    "min": "0",
    "metric": "ivb_persons_vaccinated_1plus_dose_per100"
  },
  {
    "id": "Vx_2",
    "tab": "vxTabs",
    "name": "Fully vaccinated",
    "unit": "%",
    "source": "World Health Organization",
    "source_file": "ivb",
    "risk_dir": "desc",
    "risk_2": "60",
    "risk_3": "40",
    "risk_4": "20",
    "risk_5": "10",
    "risk_level": "3",
    "value": "36",
    "count": "190",
    "total": "6914",
    "mean": "36",
    "stddev": "26",
    "max": "118",
    "min": "0",
    "metric": "ivb_persons_fully_vaccinated_per100"
  },
  {
    "id": "Vx_3",
    "tab": "vxTabs",
    "name": "Vaccines available",
    "unit": "%",
    "source": "WHO-IMF",
    "source_file": "imf_procurement",
    "risk_dir": "desc",
    "risk_2": "120",
    "risk_3": "80",
    "risk_4": "40",
    "risk_5": "20",
    "risk_level": "2",
    "value": "120",
    "count": "186",
    "total": "22460",
    "mean": "120",
    "stddev": "105",
    "max": "495",
    "min": "28",
    "metric": "imf_procurement"
  },
  {
    "id": "Dx_1",
    "tab": "dxTabs",
    "name": "Positive test rate",
    "unit": "%",
    "source": "National government reports",
    "source_file": "owd",
    "risk_dir": "asc",
    "risk_1": "3",
    "risk_2": "10",
    "risk_3": "20",
    "risk_4": "30",
    "risk_level": "2",
    "value": "8",
    "count": "51",
    "total": "414",
    "mean": "8",
    "stddev": "10",
    "max": "42",
    "min": "0",
    "metric": "owd_positive_rate"
  },
  {
    "id": "Dx_2",
    "tab": "dxTabs",
    "name": "Total Tests",
    "unit": "per 100k",
    "source": "National government reports",
    "source_file": "owd",
    "risk_dir": "desc",
    "risk_2": "75",
    "risk_3": "50",
    "risk_4": "25",
    "risk_5": "10",
    "risk_level": "3",
    "value": "15",
    "count": "48",
    "total": "749",
    "mean": "15",
    "stddev": "26",
    "max": "167",
    "min": "0",
    "metric": "owd_total_tests_per_100"
  },
  {
    "id": "Tx_1",
    "tab": "txTabs",
    "name": "Hospital admissions",
    "unit": "per 1m",
    "source": "European CDC for EU countries, government sources for other countries",
    "source_file": "owd",
    "risk_dir": "asc",
    "risk_1": "1",
    "risk_2": "10",
    "risk_3": "25",
    "risk_4": "50",
    "risk_level": "3",
    "value": "19",
    "count": "7",
    "total": "133",
    "mean": "19",
    "stddev": "12",
    "max": "40",
    "min": "0",
    "metric": "owd_icu_patients_per_million"
  },
  {
    "id": "Tx_2",
    "tab": "txTabs",
    "name": "ICU admissions",
    "unit": "per 1m",
    "source": "European CDC for EU countries, government sources for other countries",
    "source_file": "owd",
    "risk_dir": "asc",
    "risk_1": "10",
    "risk_2": "100",
    "risk_3": "250",
    "risk_4": "500",
    "risk_level": "3",
    "value": "230",
    "count": "6",
    "total": "1382",
    "mean": "230",
    "stddev": "337",
    "max": "979",
    "min": "30",
    "metric": "owd_hosp_patients_per_million"
  },
  {
    "id": "Tx_3",
    "tab": "txTabs",
    "name": "Case fatality ratio",
    "unit": "%",
    "source": "World Health Organization",
    "source_file": "epi",
    "risk_dir": "asc",
    "risk_1": "1",
    "risk_2": "2",
    "risk_3": "3",
    "risk_4": "4",
    "risk_level": "2",
    "value": "1",
    "count": "191",
    "total": "377",
    "mean": "1",
    "stddev": "1",
    "max": "19",
    "min": "0",
    "metric": "case_fatality"
  }
];